import { StyleSheet } from 'react-native';

export const primaryGreen = '#05b163';

const styles = StyleSheet.create({
  card: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 17,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  cardLabel: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
  },
  cardValue: {
    color: '#202124',
    fontSize: 17,
    fontWeight: '800',
    marginTop: 7,
  },
  content: {
    backgroundColor: '#f7f9fa',
    padding: 18,
    rowGap: 14,
  },
  divider: {
    backgroundColor: '#edf0f2',
    height: 1,
    marginHorizontal: -18,
    marginTop: 14,
  },
  greenIconBox: {
    alignItems: 'center',
    backgroundColor: '#eef8f3',
    borderRadius: 15,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  greenText: {
    color: primaryGreen,
    fontSize: 13,
    fontWeight: '800',
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#edf0f2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    height: 58,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  headerButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerMeta: {
    alignItems: 'center',
    columnGap: 3,
    flexDirection: 'row',
  },
  headerTitle: {
    color: '#202124',
    fontSize: 18,
    fontWeight: '800',
  },
  historyRow: {
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 14,
  },
  historyRowBorder: {
    borderBottomColor: '#edf0f2',
    borderBottomWidth: 1,
  },
  lotRow: {
    alignItems: 'center',
    flexDirection: 'row',
    paddingTop: 13,
  },
  lotText: {
    color: '#5f6368',
    flex: 1.15,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
  },
  productBrand: {
    color: '#6f747b',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 7,
  },
  productImageCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 2,
    height: 92,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    width: 92,
  },
  productName: {
    color: '#202124',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 25,
  },
  rowDate: {
    color: '#30343a',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
  },
  rowQuantity: {
    color: '#5f6368',
    flex: 0.62,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  rowStatus: {
    color: '#30343a',
    fontSize: 13,
    fontWeight: '700',
  },
  safeArea: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  sectionCard: {
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    padding: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#202124',
    fontSize: 16,
    fontWeight: '800',
  },
  statusCell: {
    alignItems: 'center',
    columnGap: 7,
    flex: 0.82,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  statusDot: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  stockUnit: {
    color: '#5f6368',
    fontSize: 16,
    fontWeight: '800',
  },
  stockValue: {
    color: primaryGreen,
    fontSize: 38,
    fontWeight: '800',
  },
  stockValueRow: {
    alignItems: 'baseline',
    columnGap: 7,
    flexDirection: 'row',
    marginTop: 3,
  },
  subTitle: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 14,
  },
  summary: {
    alignItems: 'center',
    columnGap: 16,
    flexDirection: 'row',
    paddingBottom: 2,
  },
  summaryText: {
    flex: 1,
  },
});

export default styles;
