import { StyleSheet } from 'react-native';

export const primaryGreen = '#05b163';

const styles = StyleSheet.create({
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 14,
  },
  content: {
    backgroundColor: '#f7f9fa',
    padding: 18,
    paddingBottom: 28,
    rowGap: 14,
  },
  detailButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#cfeedd',
    borderRadius: 16,
    borderWidth: 1,
    columnGap: 8,
    flexDirection: 'row',
    height: 54,
    justifyContent: 'center',
  },
  detailButtonPressed: {
    backgroundColor: '#f5fbf8',
  },
  detailButtonText: {
    color: primaryGreen,
    fontSize: 15,
    fontWeight: '800',
  },
  emptyButton: {
    alignItems: 'center',
    backgroundColor: primaryGreen,
    borderRadius: 14,
    columnGap: 8,
    flexDirection: 'row',
    height: 48,
    justifyContent: 'center',
    marginTop: 18,
    paddingHorizontal: 18,
  },
  emptyButtonPressed: {
    backgroundColor: '#19c978',
  },
  emptyButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 16,
    borderWidth: 1,
    padding: 24,
  },
  emptyText: {
    color: '#6f747b',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 8,
    textAlign: 'center',
  },
  emptyTitle: {
    color: '#202124',
    fontSize: 17,
    fontWeight: '800',
    marginTop: 10,
    textAlign: 'center',
  },
  field: {
    backgroundColor: '#ffffff',
    borderColor: '#e5e8eb',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 16,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  greenText: {
    color: primaryGreen,
    fontSize: 13,
    fontWeight: '800',
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#edf0f2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    height: 58,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  headerButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerTitle: {
    color: '#202124',
    fontSize: 18,
    fontWeight: '800',
  },
  infoCard: {
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    flex: 1,
    minHeight: 128,
    minWidth: 150,
    padding: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  infoLabel: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
  },
  infoMeta: {
    color: '#5f6368',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
  },
  infoValue: {
    color: '#202124',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 14,
  },
  input: {
    color: '#202124',
    fontSize: 16,
    fontWeight: '700',
    padding: 0,
  },
  label: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
  },
  lotAside: {
    alignItems: 'flex-end',
    rowGap: 7,
  },
  lotCode: {
    color: '#202124',
    fontSize: 15,
    fontWeight: '800',
  },
  lotMain: {
    flex: 1,
    paddingRight: 12,
  },
  lotMeta: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
  },
  lotQuantity: {
    color: '#30343a',
    fontSize: 14,
    fontWeight: '800',
  },
  lotRow: {
    alignItems: 'center',
    borderTopColor: '#edf0f2',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 14,
  },
  matchIcon: {
    alignItems: 'center',
    backgroundColor: '#eef8f3',
    borderRadius: 14,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  matchImage: {
    backgroundColor: '#eef8f3',
    borderRadius: 14,
    height: 40,
    width: 40,
  },
  matchInfo: {
    flex: 1,
  },
  matchMeta: {
    color: '#6f747b',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  matchName: {
    color: '#202124',
    fontSize: 15,
    fontWeight: '800',
  },
  matchRow: {
    alignItems: 'center',
    borderTopColor: '#edf0f2',
    borderTopWidth: 1,
    columnGap: 12,
    flexDirection: 'row',
    marginTop: 14,
    paddingTop: 14,
  },
  matchRowPressed: {
    opacity: 0.72,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: primaryGreen,
    borderRadius: 14,
    columnGap: 8,
    flex: 1,
    flexDirection: 'row',
    height: 50,
    justifyContent: 'center',
    minWidth: 154,
  },
  primaryButtonPressed: {
    backgroundColor: '#19c978',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  productIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 2,
    height: 92,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    width: 92,
  },
  productImage: {
    borderRadius: 16,
    height: 88,
    width: 88,
  },
  productMeta: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 7,
  },
  productName: {
    color: '#202124',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 25,
  },
  safeArea: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  scanner: {
    height: 240,
  },
  scannerContainer: {
    borderRadius: 14,
    marginTop: 14,
    overflow: 'hidden',
  },
  scannerHelp: {
    backgroundColor: '#202124',
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlign: 'center',
  },
  searchCard: {
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    padding: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  searchHeader: {
    alignItems: 'center',
    columnGap: 12,
    flexDirection: 'row',
  },
  searchIcon: {
    alignItems: 'center',
    backgroundColor: '#eef8f3',
    borderRadius: 16,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  searchSubtitle: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 4,
  },
  searchTitle: {
    color: '#202124',
    fontSize: 18,
    fontWeight: '800',
  },
  searchTitleGroup: {
    flex: 1,
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: '#cfeedd',
    borderRadius: 14,
    borderWidth: 1,
    columnGap: 8,
    flexDirection: 'row',
    height: 50,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  secondaryButtonPressed: {
    backgroundColor: '#f5fbf8',
  },
  secondaryButtonText: {
    color: primaryGreen,
    fontSize: 15,
    fontWeight: '800',
  },
  sectionCard: {
    backgroundColor: '#ffffff',
    borderColor: '#eef0f3',
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    padding: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#202124',
    fontSize: 16,
    fontWeight: '800',
  },
  statusDot: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  statusRow: {
    alignItems: 'center',
    columnGap: 7,
    flexDirection: 'row',
  },
  statusText: {
    color: '#30343a',
    fontSize: 13,
    fontWeight: '700',
  },
  stockValue: {
    color: primaryGreen,
    fontSize: 38,
    fontWeight: '800',
    marginTop: 8,
  },
  summaryCard: {
    alignItems: 'center',
    columnGap: 16,
    flexDirection: 'row',
  },
  summaryInfo: {
    flex: 1,
  },
});

export default styles;
