import { StyleSheet } from 'react-native';

const primaryGreen = '#05b163';

const styles = StyleSheet.create({
  barcodeActions: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  content: {
    backgroundColor: '#ffffff',
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  field: {
    backgroundColor: '#ffffff',
    borderColor: '#e5e8eb',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minWidth: 150,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  foundCard: {
    alignItems: 'center',
    backgroundColor: '#f5fbf8',
    borderColor: '#d8f0e4',
    borderRadius: 14,
    borderWidth: 1,
    columnGap: 12,
    flexDirection: 'row',
    padding: 14,
  },
  foundIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  foundInfo: {
    flex: 1,
  },
  foundName: {
    color: '#202124',
    fontSize: 16,
    fontWeight: '800',
  },
  foundText: {
    color: '#5f6368',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 5,
  },
  helpText: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 12,
  },
  input: {
    color: '#202124',
    fontSize: 16,
    fontWeight: '700',
    padding: 0,
  },
  label: {
    color: '#6f747b',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
  },
  lotField: {
    marginTop: 12,
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(20, 24, 28, 0.58)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    maxWidth: 420,
    padding: 22,
    width: '100%',
  },
  modalField: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe4e7',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  modalIcon: {
    alignItems: 'center',
    backgroundColor: '#eef8f3',
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  modalPrimaryButton: {
    alignItems: 'center',
    backgroundColor: primaryGreen,
    borderRadius: 14,
    height: 52,
    justifyContent: 'center',
    marginTop: 16,
  },
  modalText: {
    color: '#5f6368',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    marginTop: 8,
  },
  modalTitle: {
    color: '#202124',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 14,
  },
  notFoundCard: {
    alignItems: 'center',
    backgroundColor: '#fff8ef',
    borderColor: '#ffe3bd',
    borderRadius: 14,
    borderWidth: 1,
    columnGap: 9,
    flexDirection: 'row',
    marginBottom: 12,
    padding: 13,
  },
  notFoundText: {
    color: '#5f6368',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  safeArea: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: primaryGreen,
    borderRadius: 16,
    columnGap: 8,
    elevation: 3,
    flexDirection: 'row',
    height: 58,
    justifyContent: 'center',
    marginTop: 26,
    shadowColor: primaryGreen,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
  },
  saveButtonPressed: {
    backgroundColor: '#19c978',
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  scanButton: {
    alignItems: 'center',
    backgroundColor: primaryGreen,
    borderRadius: 14,
    columnGap: 7,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  scanButtonPressed: {
    backgroundColor: '#19c978',
  },
  scanButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  scanner: {
    height: 240,
  },
  scannerContainer: {
    borderRadius: 14,
    marginTop: 12,
    overflow: 'hidden',
  },
  scannerHelp: {
    backgroundColor: '#202124',
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlign: 'center',
  },
  searchButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: '#cfeedd',
    borderRadius: 14,
    borderWidth: 1,
    columnGap: 7,
    flexDirection: 'row',
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  searchButtonPressed: {
    backgroundColor: '#f5fbf8',
  },
  searchButtonText: {
    color: primaryGreen,
    fontSize: 14,
    fontWeight: '800',
  },
});

export default styles;
